export interface Staff{
    id: string,
    initial: string,
    fname: string,
    lname: string,
    contact: string,
    streetNo: string,
    firstStreet: string,
    secondStreet: string,
    town: string,
    gender: string,
    salaryNo: string,
    active: boolean,
    role: string,
    image: string,
}
